{% set name = "pyscaffold" %}
{% set version = "4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyScaffold-{{ version }}.tar.gz
  sha256: 7012ae5f9c95b910a39a099824104dc888beb932de86b07514882f3511bc6c74

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - putup = pyscaffold.cli:run


requirements:
  host:
    - python >=3
    - pip
    - setuptools_scm >=5
  run:
    - python >=3
    - importlib-metadata
    - appdirs >=1.4.4,<2
    - configupdater >=1.1.3,<2
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - tomlkit >=0.7.0,<2
    - packaging >=20.7

test:
  imports:
    - pyscaffold
    - pyscaffold.templates
  commands:
    - putup --help
    - pytest -m "not skip_on_conda_build" --cov-config setup.cfg
    - pip install path.py  # Workaround for https://github.com/man-group/pytest-plugins/pull/174
    - pip check
  source_files:
    - tests
    - setup.cfg
  requires:
    - git
    - pip
    - setuptools
    - tomlkit
    - certifi
    - tox
    - python-build
    - pre-commit
    - sphinx
    - flake8
    - virtualenv
    - pytest
    - pytest-cov
    - pytest-shutil
    - pytest-virtualenv
    - pytest-fixture-config
    - pytest-xdist
    - twine

about:
  home: http://pyscaffold.org/
  license: MIT
  license_file: LICENSE.txt
  summary: Template tool for putting up the scaffold of a Python project
  dev_url: https://github.com/pyscaffold/pyscaffold/

extra:
  recipe-maintainers:
    - ocefpaf
    - maresb
    - FlorianWilhelm
